version: "3.9"
services:
    db:
        build: ./DB
        environment:
            - POSTGRES_PASSWORD=example
        restart: always
        ports:
            - "5432:5432"

    api:
        build: ./API
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - DatabaseSettings.ConnectionString=User ID=postgres;Password=example;Host=db;Port=5432;Database=myDataBase;Connection Lifetime=0;
        ports:
            - 45321:80
        restart: always
        depends_on:
            - db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db