version: "3.9"
services:
    db:
        build: ./DB
        environment:
            - POSTGRES_PASSWORD=example
        restart: always
        ports:
            - "5432:5432"

    api:
        build: ./API
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            # - CacheSettings:CacheStrategy=Probabilistic
            - CacheSettings:CacheStrategy=Simple
            - CacheSettings:CacheLifeTimeInMinutes=2
            - DatabaseSettings.ConnectionString=User ID=postgres;Password=example;Host=db;Port=5432;Database=myDataBase;Connection Lifetime=0;
        ports:
            - 45321:80
        restart: always
        depends_on:
            - db

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db

    siege_get:
        build: ./Siege
        restart: always
        command: -c500 -r3000 api/info
        depends_on:
            - api

    siege_post:
        build: ./Siege
        restart: always
        command: -c1 -r2000 'http://api/info/ POST'
        depends_on:
            - api
            
    prometheus:
        image: prom/prometheus
        ports: 
            - 900:9090
        volumes:
            - ./prometheus/config:/etc/prometheus
        depends_on:
            - api
    graphana:
        image: grafana/grafana
        ports:  
            - 3000:3000
        depends_on:
            - prometheus
        volumes:
            - ./grafana_data:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/

