version: "3.9"
services:
    db:
        build: ./DB
        environment:
            - POSTGRES_PASSWORD=example
        restart: always
        ports:
            - "5432:5432"

    api:
        build: ./API/API
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=aqwe123
        restart: always
        

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        depends_on:
            - db